### ISSUE TITLE
Error Fetching Data

### ISSUE THREAD

**Issue by Jigar3** [kaushiknishchay/indian-stock-exchange#1]
This is the error in Browser.
Code is attached below
![ss](https://user-images.githubusercontent.com/32068121/41808099-4b263b4c-76f6-11e8-80bd-8890ad6266db.jpg)

```
const stock = require('indian-stock-exchange');

stock.NSE.getQuoteInfo(symbol).then(data => {
      console.log(data);
    }).catch((e) => {
      console.log(e)
    })
```

**Comment by kaushiknishchay** [comment]
Generally browsers send a 'OPTION' request before actually making a call to the API endpoint, during which it is checked if server allows the request.

Also the 'Referer' header arent allowed on browser side to be modified.

You can either make the api call on your server or in a mobile app (eg. react-native mobile app).
